name: Deploy

on: 
  workflow_dispatch:
  push:
    branches: [ main, develop ]

jobs:
  test-ci:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        go: [ '1.14', '1.17' ]
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go mod tidy
      - run: go test -v ./...

  deploy-test:
    needs: test-ci
    env:
      IMAGE_TAG: ${{ github.sha }}
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-20.04
    concurrency: deploy-to-dev
    environment: dev
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          go-version: ${{ matrix.go }}
          
      - name: Build docker image
        run: docker build -t lucasmocerinomonteiro/setup-go:$IMAGE_TAG .
        
      - name: Deploy..
        run: echo "Deploy to Dev..."