name: CI Tests

on:
  push:
  pull_request:

jobs:
  test-ci:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        go: [ '1.14', '1.17' ]
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go mod tidy
      - run: go test -v ./...